// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQsZjJHUGNUSgPuF-DA6UASrBbXit4VY8',
    appId: '1:124739643133:web:a28e88cf036b55afebc094',
    messagingSenderId: '124739643133',
    projectId: 'delivery-app-8cthnp',
    authDomain: 'delivery-app-8cthnp.firebaseapp.com',
    storageBucket: 'delivery-app-8cthnp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYxZLPnVviWv4dbXEUbbcdnkzdBDCJj3w',
    appId: '1:124739643133:android:f94a5351d5e8b09febc094',
    messagingSenderId: '124739643133',
    projectId: 'delivery-app-8cthnp',
    storageBucket: 'delivery-app-8cthnp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtWC5JM-Fo1Bf_4p65y65YLXB_dR0vR_U',
    appId: '1:124739643133:ios:2fe810ead8cc8c4febc094',
    messagingSenderId: '124739643133',
    projectId: 'delivery-app-8cthnp',
    storageBucket: 'delivery-app-8cthnp.appspot.com',
    iosBundleId: 'com.example.flutterDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtWC5JM-Fo1Bf_4p65y65YLXB_dR0vR_U',
    appId: '1:124739643133:ios:2fe810ead8cc8c4febc094',
    messagingSenderId: '124739643133',
    projectId: 'delivery-app-8cthnp',
    storageBucket: 'delivery-app-8cthnp.appspot.com',
    iosBundleId: 'com.example.flutterDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQsZjJHUGNUSgPuF-DA6UASrBbXit4VY8',
    appId: '1:124739643133:web:c45b7c695c09e1faebc094',
    messagingSenderId: '124739643133',
    projectId: 'delivery-app-8cthnp',
    authDomain: 'delivery-app-8cthnp.firebaseapp.com',
    storageBucket: 'delivery-app-8cthnp.appspot.com',
  );
}
